package com.vegasega.streetsaarthi.networking

const val BASE_URL = "http://139.59.36.95:8081/"
const val WEB_URL = "https://streetsaarthi.in/"

//const val BASE_URL = "http://167.71.225.20:8081/"
//const val WEB_URL = "http://167.71.225.20:8080/"

const val URL = BASE_URL+"api/"


const val RAZORPAY_KEY = "rzp_test_Ce5CQWqb8wSD9U"
//const val RAZORPAY_KEY = "rzp_live_aLCUvxiL7fqmo3"

//const val RAZORPAY_KEY = "rzp_test_D9A5zJDG5T5C8b"
//const val RAZORPAY_KEY = "rzp_live_Wkrn25TUl3UUAn"

const val MOBILE_TOKEN = "update-mobile-token"
const val LOGIN = "login"
const val VENDER_PROFILE = "vendor-profile"
const val VENDER_PROFILE_UPDATE = "vendor-profile-update"
const val SEND_OTP = "send-otp"
const val VERIFY_OTP = "verify-otp"
const val SIGN_UP = "vendor-signup"
const val RESEND_OTP = "resend-otp"
const val PASSWORD_UPDATE = "password-update"



const val STATE = "state-list?page=1"
const val DISTRICT = "district-list"
const val PANCHAYAT = "panchayat-list"
const val PINCODE = "pincode-list"
const val LOCAL_ORGANISATION = "local-organisation"
const val Vending = "vending-list?page=1"
const val Marketplace = "marketplace-list?page=1"
const val SchemeHistoryList = "scheme-history-list"

const val LiveScheme = "live-scheme"
const val NoticeLiveList = "notice-live-list"
const val LiveTraining = "live-training"

const val ComplaintFeedback = "feedback-history-all"
const val ComplaintFeedbackHistory = "feedback-history-user"
const val InformationCenter = "information-history-list"
const val ADS_LIST = "ads-list?page=1"

const val SchemeApply = "scheme-apply"
const val SchemeDetail = "scheme-detail"
const val TrainingDetail = "training-detail"
const val NoticeDetail = "notice-detail"
const val InformationDetail = "information-detail"


const val AllSchemeHistory = "user-scheme-history-list"
const val AllTrainingHistory = "training-list"
const val AllNoticeHistory = "notice-history-list"

const val Notifications = "notification-list"
const val DeleteNotification = "delete-notification"
const val UpdateNotification = "notification-update"


const val FeedbackConversationDetails = "feedback-conversation-details"
const val AddFeedbackConversation = "feedback-conversation"

const val Complaint_Type = "complaint-type"
const val NewFeedback = "new-feedback"
const val SaveSettings = "save-settings"
const val LOGOUT = "logout"
const val PasswordUpdate = "password-update"
const val UpdateNomineeDetails = "update-nominee-details"
const val NomineeDetails = "nominee-details"
const val Subscription = "subscription"
const val CouponLiveList = "coupon-live-list"
const val PurchaseSubscription = "purchase-subscription"
const val TransactionHistory = "transaction-history"
const val TransactionDetails = "transaction-details"


const val mobile_no = "mobile_no"
const val slug = "slug"
const val forgot = "forgot"
const val user_type = "user_type"
const val otp = "otp"
const val mobile_number = "mobile_number"
const val password = "password"
const val login = "login"
const val mobile_token = "mobile_token"
const val user_id = "user_id"
const val vendor_first_name = "vendor_first_name"
const val vendor_last_name = "vendor_last_name"
const val signup = "signup"
const val user_role = "user_role"
const val parent_first_name = "parent_first_name"
const val parent_last_name = "parent_last_name"
const val gender = "gender"
const val date_of_birth = "date_of_birth"
const val social_category = "social_category"
const val education_qualification = "education_qualification"
const val marital_status = "marital_status"
const val spouse_name = "spouse_name"
const val residential_state = "residential_state"
const val residential_district = "residential_district"
const val residential_municipality_panchayat = "residential_municipality_panchayat"
const val residential_pincode = "residential_pincode"
const val residential_address = "residential_address"
const val type_of_marketplace = "type_of_marketplace"
const val marketpalce_others = "marketpalce_others"
const val type_of_vending = "type_of_vending"
const val vending_others = "vending_others"
const val total_years_of_business = "total_years_of_business"
const val vending_time_from = "vending_time_from"
const val vending_time_to = "vending_time_to"
const val vending_state = "vending_state"
const val vending_district = "vending_district"
const val vending_municipality_panchayat = "vending_municipality_panchayat"
const val vending_pincode = "vending_pincode"
const val vending_address = "vending_address"
const val local_organisation = "local_organisation"
const val vending_documents = "vending_documents"
const val availed_scheme = "availed_scheme"
const val profile_image_name = "profile_image_name"
const val identity_image_name = "identity_image_name"
const val shop_image = "shop_image"
const val cov_image = "cov_image"
const val lor_image = "lor_image"
const val survey_receipt_image = "survey_receipt_image"
const val challan_image = "challan_image"
const val approval_letter_image = "approval_letter_image"
const val state_id = "state_id"
const val district_id = "district_id"
const val delete_account = "delete_account"
const val type = "type"
const val subject = "subject"
const val complaint_type = "complaint_type"
const val name = "name"
const val message = "message"
const val media = "media"
const val statusFrom = "status"
const val municipality_id = "municipality_id"
const val page = "page"
const val search_input = "search_input"
const val feedback_id = "feedback_id"
const val reply = "reply"
const val is_read = "is_read"
const val member_id = "member_id"
const val nomineeSquare = "nominee[]"
const val scheme_id = "scheme_id"
const val notification = "notification"
const val language = "language"
const val transaction_id = "transaction_id"
const val no_of_month_year = "no_of_month_year"
const val month_year = "month_year"
const val membership_id = "membership_id"
const val order_id = "order_id"
const val date_time = "date_time"
const val plan_type = "plan_type"
const val payment_method = "payment_method"
const val payment_status = "payment_status"
const val payment_validity = "payment_validity"
const val net_amount = "net_amount"
const val coupon_discount = "coupon_discount"
const val coupon_amount = "coupon_amount"
const val gst_rate = "gst_rate"
const val gst_amount = "gst_amount"
const val total_amount = "total_amount"



const val USER_TYPE = "member"
const val PING = "8.8.8.8"


//const val TRANSLATE_URL = "https://translation.googleapis.com/language/"
//const val TRANSLATE = "translate/v2?key="

const val TRANSLATE_URL = "https://translate.googleapis.com/translate_a/"
const val TRANSLATE = "single?client=gtx&sl=en&dt=t"


const val Screen = "screen"
const val Start = "Start"
const val Main = "Main"
const val CompleteRegister = "CompleteRegister"
const val LoginPassword = "LoginPassword"
const val LoginOtp = "LoginOtp"

const val IS_LANGUAGE = true
const val IS_LANGUAGE_ALL = false

const val RETRY_COUNT = 1

